packages:
  - "."

savePrefix: ""
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
verifyDepsBeforeRun: error
strictDepBuilds: true

allowBuilds:
  esbuild: true
  sharp: true
  vnu-jar: true
